### PR TITLE
Set up basic infrastructure for testing in chinese, turkish and dutch

### PR DESCRIPTION
**Pull request by leokim-l**
@KyranWissink 
@gracsh 
@aslgraefe 
(Hope I tagged the right people), could you pull this branch, add the tests by commiting to this branch? Whenever all of these are done I can merge it into develop. Feel free to contact me for any questions :)

### CODE REVIEW

**Comment by leokim-l** [comment]
As a reference, I copy pasted from the italian (random choice), since the English one is slightly different (is this OK @pnrobinson ?). Whenever you find Italian in the one file there is, translate that (or rather, what is in the same place in the English version...) into the respective language. E.g.

https://github.com/monarch-initiative/phenopacket2prompt/blob/7fb36c436c071dcd527d5e592471f1b7f2d5a81f/src/test/java/org/monarchinitiative/phenopacket2prompt/output/impl/dutch/PpktIndividualDutchTest.java#L24

there is the italian sentence, go to 

https://github.com/monarch-initiative/phenopacket2prompt/blob/7fb36c436c071dcd527d5e592471f1b7f2d5a81f/src/test/java/org/monarchinitiative/phenopacket2prompt/output/impl/english/PpktIndividualEnglishTest.java#L25

and translate into chinese/turkish/dutch. Careful that the translation needs to reflect *exactly* the structure of what you used in the main source code.

**Comment by aslgraefe** [comment]
@leokim-l I see this now, I will get to this later! Sorry for the delay

**Comment by aslgraefe** [comment]
@leokim-l  please check my comment in #68 , I can't find the test files for Turkish

**Comment by leokim-l** [comment]
Various efforts happened in separate branches.

**Pull request closed without merging**
